# Generated by Django 2.2.4 on 2019-12-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20191130_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='memocomment',
            name='user',
        ),
        migrations.AddField(
            model_name='memo',
            name='Member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='finance.Member'),
        ),
        migrations.AddField(
            model_name='memocomment',
            name='Member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='memoComment', to='finance.Member'),
        ),
    ]
