# Generated by Django 2.2.4 on 2019-12-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20191201_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memocomment',
            name='Member_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.Member'),
        ),
    ]
